### ISSUE TITLE
Crash caused when json file is access via http (instead of https)

### ISSUE THREAD

**Issue by mikemee** [eggheadgames/Siren#14]
If the JSON version file is stored on an http server and is not available via https, then the library will cause a crash like this:
```
01-24 11:36:58.578 28106-28297/com.example E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
     Process: com.example, PID: 28106
     java.lang.RuntimeException: An error occurred while executing doInBackground()
         at android.os.AsyncTask$3.done(AsyncTask.java:325)
         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
         at java.lang.Thread.run(Thread.java:761)
      Caused by: java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
         at com.eggheadgames.siren.Siren$LoadJsonTask.doInBackground(Siren.java:266)
         at com.eggheadgames.siren.Siren$LoadJsonTask.doInBackground(Siren.java:258)
         at android.os.AsyncTask$2.call(AsyncTask.java:305)
         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
         at java.lang.Thread.run(Thread.java:761) 

```

This seems to have been introduced by #10 / #11 whereby the code now only works if the JSON file is fetched via https.

We should make two fixes:

- [ ] allow an `http` url to be fetched (not just `https`)
- [ ] silently fail, except for a debug log message, instead of crashing, if there is an error fetching the json file

**Comment by bre7** [comment]
Any idea why was this happening ? HttpsURLConnection extends HttpURLConnection after all.
